module PrestaShop
    RESOURCES = %w{ addresses
                    carriers
                    cart_rules
                    carts
                    categories
                    combinations
                    configurations
                    contacts
                    content_management_system
                    countries
                    currencies
                    customer_messages
                    customer_threads
                    customers
                    deliveries
                    employees
                    groups
                    guests
                    image_types
                    images
                    images/general/header
                    images/general/mail
                    images/general/invoice
                    images/general/store_icon
                    images/products
                    images/categories
                    images/manufacturers
                    images/suppliers
                    images/stores
                    languages
                    manufacturers
                    order_carriers
                    order_details
                    order_discounts
                    order_histories
                    order_invoices
                    order_payments
                    order_states
                    orders
                    price_ranges
                    product_feature_values
                    product_features
                    product_option_values
                    product_options
                    product_suppliers
                    products
                    search
                    shop_groups
                    shops
                    specific_price_rules
                    specific_prices
                    states
                    stock_availables
                    stock_movement_reasons
                    stock_movements
                    stocks
                    stores
                    suppliers
                    supply_order_details
                    supply_order_histories
                    supply_order_receipt_histories
                    supply_order_states
                    supply_orders
                    tags
                    tax_rule_groups
                    tax_rules
                    taxes
                    translated_configurations
                    warehouse_product_locations
                    warehouses
                    weight_ranges
                    zones 
    }
end